<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>abackTop</name>
   <tag></tag>
   <elementGuidId>4ac82742-db83-4f1c-be59-f1a4e406dd2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='backTop']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#backTop</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2fa46ead-cc46-445a-816f-282c89d3f167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>backTop</value>
      <webElementGuid>c8d6d5c7-2b41-4cac-8942-d7df25e2dde6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-back-top bg-teal</value>
      <webElementGuid>fc339523-33b3-43d5-81a2-fc16394ba040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;backTop&quot;)</value>
      <webElementGuid>423d813c-215b-4419-ace2-3b7e794dc7c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='backTop']</value>
      <webElementGuid>aa5267f0-1112-4b5a-979f-6bbd8e17fcea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/a</value>
      <webElementGuid>4dcb5f22-378e-4675-a4c2-061fa8c3b309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'backTop']</value>
      <webElementGuid>fc5c0c5c-c6c2-4158-9124-80442fc87415</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
