<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divsidebar-overlay</name>
   <tag></tag>
   <elementGuidId>8988afae-50a2-4e07-87c1-ad2e84398aa9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sidebar-overlay']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sidebar-overlay</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b798f70b-82d6-4266-9ebd-11a1974d949e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sidebar-overlay</value>
      <webElementGuid>dee39a55-fbe1-4cfe-a1bc-a7c508fa3b08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sidebar-overlay&quot;)</value>
      <webElementGuid>45e2d083-042a-4080-91a1-6bbaac726e36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='sidebar-overlay']</value>
      <webElementGuid>31a51d47-72d0-42d7-acb4-d39d4913e2a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]</value>
      <webElementGuid>ab3ee20f-f661-4b8c-ac0e-fb9dfda2f2fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'sidebar-overlay']</value>
      <webElementGuid>5c7c04b0-7b35-4496-8fe1-dca33ca8b396</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
