<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Dashboard</name>
   <tag></tag>
   <elementGuidId>7833de14-e491-461f-8cd6-d59675f0e844</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.content-header > h1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>afd83b1b-9b55-438f-a570-5f1cdf52755d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Dashboard
</value>
      <webElementGuid>210a486a-2f0d-4d2f-9145-9b46b9206433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;k-webkit k-webkit120&quot;]/body[@class=&quot;sidebar-mini layout-fixed control-sidebar-slide-open sidebar-closed sidebar-collapse&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;content-wrapper&quot;]/div[@class=&quot;content-header&quot;]/h1[1]</value>
      <webElementGuid>23001339-bda5-4eef-9a41-a16fd8828350</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/h1</value>
      <webElementGuid>9b250f67-71f8-49dd-b067-aa38cace2c30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = '
Dashboard
' or . = '
Dashboard
')]</value>
      <webElementGuid>74c73e91-af36-4a6f-b0c4-2643aa85ba30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
