<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Admin email adminyourstore.com Admin pass_11085b</name>
   <tag></tag>
   <elementGuidId>1d4b02ff-8e48-49a0-8e2e-229fb263b7ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>f828228f-36c2-4bd8-8c28-02ee9c9b5819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Admin email: admin@yourstore.com Admin password: admin </value>
      <webElementGuid>377cfdda-d4a8-4160-b5e9-8cddceb8d117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;html-login-page&quot;]/body[1]/div[@class=&quot;master-wrapper-page&quot;]/div[@class=&quot;master-wrapper-content&quot;]/div[@class=&quot;master-column-wrapper&quot;]/div[@class=&quot;center-1&quot;]/div[@class=&quot;page login-page&quot;]/div[@class=&quot;page-body&quot;]/div[@class=&quot;topic-block&quot;]/div[@class=&quot;topic-block-body&quot;]/p[1]</value>
      <webElementGuid>942b0a48-ac59-42fb-ade8-52590618aa4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>d96aa0e5-316a-42a7-85c2-2cf736d662f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Admin email: admin@yourstore.com Admin password: admin ' or . = 'Admin email: admin@yourstore.com Admin password: admin ')]</value>
      <webElementGuid>b8de54af-e2c0-4b4c-9413-1330d6b0a3c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
